### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by bond15** [ToposInstitute/poly#5]
I'd like to help contribute any (Agda) code examples to the Poly book. :)

Here's some samples of what I've been working on so far. (see ToposPoly directory).

https://gist.github.com/bond15/1d56e4a605e302498fceb1dae0f03f45
ex. Turing machine as natural transformation of polynomial functors.

https://github.com/bond15/Polynomials-Categorically/tree/master/ToposPoly
Sandbox where I've been slowly encoding things from the book.

- Eric

**Comment by daig** [comment]
Nice!
